# Fattorizzazione di Cholesky

La fattorizzazione di Cholesky è una variante particolarmente efficiente della fattorizzazione $LU$. Si applica alle matrici reali **simmetriche e definite positive**.

Una matrice $A\in\mathbb{R}^{n\times n}$ è definita positiva se

$$
\mathbf{x}^TA\mathbf{x}>0
\qquad\text{per ogni }\mathbf{x}\neq\mathbf{0}.
$$

In tal caso esiste un'unica matrice triangolare inferiore $L$, con elementi diagonali positivi, tale che

$$
A=LL^T.
$$

## Risoluzione di un sistema lineare

Se $A=LL^T$, il sistema

$$
A\mathbf{x}=\mathbf{b}
$$

diventa

$$
LL^T\mathbf{x}=\mathbf{b}.
$$

Si risolvono quindi due sistemi triangolari:

$$
L\mathbf{y}=\mathbf{b},
\qquad
L^T\mathbf{x}=\mathbf{y}.
$$

```{figure} immagini_sorgente/metodo_cholesky.png
---
width: 100%
align: center
---
```
<p align="center">
  <img src="immagini_sorgente/metodo_cholesky.png" width="700">
</p>

## Calcolo degli elementi di $L$

Gli elementi del fattore vengono calcolati una colonna alla volta. Per la diagonale:

$$
\ell_{jj}=\sqrt{a_{jj}-\sum_{k=1}^{j-1}\ell_{jk}^2}.
$$

Per gli elementi sotto la diagonale:

$$
\ell_{ij}=\frac{1}{\ell_{jj}}
\left(a_{ij}-\sum_{k=1}^{j-1}\ell_{ik}\ell_{jk}\right),
\qquad i=j+1,\ldots,n.
$$

La definita positività garantisce che le quantità sotto radice siano positive. Non è quindi necessario il pivoting.

## Un esempio $3\times3$

Consideriamo la matrice simmetrica definita positiva

$$
A=
\begin{pmatrix}
4&2&2\\
2&5&1\\
2&1&5
\end{pmatrix}.
$$

La sua fattorizzazione di Cholesky è

$$
A=LL^T,
\qquad
L=
\begin{pmatrix}
2&0&0\\
1&2&0\\
1&0&2
\end{pmatrix}.
$$

Infatti

$$
LL^T=
\begin{pmatrix}
4&2&2\\
2&5&1\\
2&1&5
\end{pmatrix}=A.
$$

In [1]:
import numpy as np

A = np.array([[4., 2., 2.],
              [2., 5., 1.],
              [2., 1., 5.]])

L = np.linalg.cholesky(A)

print('L =\n', L)
print('\nErrore ||A - LL^T||_2 =', np.linalg.norm(A - L @ L.T))

L =
 [[2. 0. 0.]
 [1. 2. 0.]
 [1. 0. 2.]]

Errore ||A - LL^T||_2 = 0.0


## Soluzione del sistema

Poniamo

$$
\mathbf{b}=
\begin{pmatrix}
6\\11\\-1
\end{pmatrix}.
$$

Risolvendo prima $L\mathbf{y}=\mathbf{b}$ si ottiene

$$
\mathbf{y}=(3,4,-2)^T.
$$

Risolvendo poi $L^T\mathbf{x}=\mathbf{y}$ si ottiene

$$
\mathbf{x}=(1,2,-1)^T.
$$

In [2]:
b = np.array([6., 11., -1.])

# np.linalg.solve applicato ai due sistemi triangolari
y = np.linalg.solve(L, b)
x = np.linalg.solve(L.T, y)

print('y =', y)
print('x =', x)
print('Norma del residuo =', np.linalg.norm(b - A @ x))

y = [ 3.  4. -2.]
x = [ 1.  2. -1.]
Norma del residuo = 0.0


## Vantaggi e limiti

Rispetto alla fattorizzazione $LU$, Cholesky:

- memorizza un solo fattore triangolare;
- richiede circa $n^3/3$ operazioni, contro circa $2n^3/3$ per $LU$;
- non richiede pivoting per matrici simmetriche definite positive.

Può però essere applicata soltanto quando la matrice è simmetrica definita positiva. Se durante il calcolo compare una quantità non positiva sotto radice, le ipotesi non sono soddisfatte oppure gli effetti numerici sono rilevanti.