# 3. Operazioni sulle matrici: fattorizzazione di matrici


Molti problemi numerici diventano più semplici se, invece di lavorare direttamente con la matrice originale, la esprimiamo come prodotto di matrici dotate di una struttura particolare. Questa operazione prende il nome di **fattorizzazione** o **decomposizione matriciale**.

In forma generale, cerchiamo

$$
A=F_1F_2\cdots F_r,
$$

dove i fattori $F_1,\ldots,F_r$ sono più facili da utilizzare oppure mettono in evidenza proprietà importanti di $A$.



Fattorizzare una matrice non significa soltanto riscriverla in una forma diversa. La fattorizzazione trasforma un problema complesso in una successione di problemi più semplici.

<!-- ```{figure} immagini_sorgente/idea_fattorizzazione.png
---
width: 100%
align: center
---
```
<p align="center">
  <img src="immagini_sorgente/idea_fattorizzazione.png" width="700">
</p> -->

![](immagini_sorgente/idea_fattorizzazione.png)

La scelta dei fattori non è unica: dipende dal problema da risolvere e dalle proprietà della matrice.

### 3.1 Perché fattorizzare una matrice?

Le fattorizzazioni vengono utilizzate per:

- risolvere sistemi lineari;
- risolvere problemi ai minimi quadrati;
- calcolare autovalori e autovettori;
- calcolare valori e vettori singolari;
- determinare rango e condizionamento;
- comprimere e approssimare dati;
- separare direzioni significative da rumore o ridondanza.

Una buona fattorizzazione può offrire contemporaneamente:

1. **efficienza**, perché riduce il costo delle operazioni successive;
2. **stabilità numerica**, perché limita la propagazione degli errori di arrotondamento;
3. **interpretabilità**, perché rende visibili proprietà nascoste della matrice.

**Una prima classificazione**

Nel seguito considereremo due grandi famiglie di fattorizzazioni.

```{figure} immagini_sorgente/mappa_fattorizzazioni.png
---
width: 100%
align: center
---
```
<p align="center">
  <img src="immagini_sorgente/mappa_fattorizzazioni.png" width="700">
</p>

Le **fattorizzazioni triangolari** sono particolarmente adatte alla soluzione di sistemi lineari. Le fattorizzazioni basate su **matrici ortogonali** sono fondamentali per minimi quadrati, autovalori, valori singolari e analisi dei dati.

### 3.2 Fattorizzazione LU

L'obiettivo è rappresentare la matrice $A$ come

$$
A=LU,
$$

dove:

- $L$ è triangolare inferiore, generalmente con elementi diagonali uguali a $1$;
- $U$ è triangolare superiore.

Infatti, il sistema $A\mathbf{x}=\mathbf{b}$ diventa

$$
LU\mathbf{x}=\mathbf{b}.
$$

Ponendo $\mathbf{y}=U\mathbf{x}$, risolviamo in successione

$$
L\mathbf{y}=\mathbf{b},
\qquad
U\mathbf{x}=\mathbf{y}.
$$



L'eliminazione di Gauss trasforma $A$ in una matrice triangolare superiore $U$ eliminando, colonna dopo colonna, gli elementi al di sotto della diagonale.

Al passo $k$, per eliminare l'elemento $a_{ik}$ con $i>k$, si utilizza il moltiplicatore

$$
m_{ik}=\frac{a_{ik}^{(k)}}{a_{kk}^{(k)}}
$$

e si esegue l'operazione di riga

$$
R_i\leftarrow R_i-m_{ik}R_k.
$$

I moltiplicatori dell'eliminazione vengono memorizzati nella parte triangolare inferiore di $L$. La matrice finale dell'eliminazione è $U$.

Per una matrice densa $n\times n$, la costruzione dei fattori richiede circa

$$
\frac{2}{3}n^3
$$

operazioni in virgola mobile, mentre la soluzione dei due sistemi triangolari costa circa $2n^2$ operazioni.

**Esempio completo su una matrice $3\times3$**

Consideriamo

$$
A=
\begin{pmatrix}
2&1&1\\
4&-6&0\\
-2&7&2
\end{pmatrix}.
$$

Il primo pivot è $a_{11}=2$. I moltiplicatori della prima colonna sono

$$
m_{21}=\frac{4}{2}=2,
\qquad
m_{31}=\frac{-2}{2}=-1.
$$

Eseguiamo

$$
R_2\leftarrow R_2-2R_1,
\qquad
R_3\leftarrow R_3+R_1,
$$

ottenendo

$$
A^{(2)}=
\begin{pmatrix}
2&1&1\\
0&-8&-2\\
0&8&3
\end{pmatrix}.
$$

Il secondo moltiplicatore è

$$
m_{32}=\frac{8}{-8}=-1.
$$

Eseguiamo quindi

$$
R_3\leftarrow R_3-(-1)R_2=R_3+R_2
$$

e otteniamo la matrice triangolare superiore

$$
U=
\begin{pmatrix}
2&1&1\\
0&-8&-2\\
0&0&1
\end{pmatrix}.
$$

Inserendo i moltiplicatori sotto la diagonale unitaria costruiamo

$$
L=
\begin{pmatrix}
1&0&0\\
2&1&0\\
-1&-1&1
\end{pmatrix}.
$$

Si verifica direttamente che

$$
LU=A.
$$

### 3.3.1 Pivoting

Nell'eliminazione di Gauss il numero utilizzato come divisore al passo $k$ è il **pivot** $u_{kk}$. Per eliminare gli elementi sotto il pivot calcoliamo

$$
m_{ik}=\frac{u_{ik}}{u_{kk}},
\qquad i=k+1,\ldots,n.
$$

Possono verificarsi due problemi:

1. **Pivot nullo.** La divisione non è definita, anche se la matrice può essere non singolare.
2. **Pivot molto piccolo.** I moltiplicatori possono diventare molto grandi e amplificare gli errori di arrotondamento.

Il pivoting consiste nel riordinare opportunamente le equazioni prima di eseguire l'eliminazione.

*Un pivot nullo non implica che la matrice sia singolare*

Consideriamo

$$
A=
\begin{pmatrix}
0&1\\
1&1
\end{pmatrix}.
$$

Il primo pivot è nullo, quindi l'eliminazione senza scambi di riga non può iniziare. Tuttavia,

$$
\det(A)=-1\neq0,
$$

e la matrice è perfettamente invertibile. Basta scambiare le due righe:

$$
P=
\begin{pmatrix}
0&1\\
1&0
\end{pmatrix},
\qquad
PA=
\begin{pmatrix}
1&1\\
0&1
\end{pmatrix}.
$$

Dopo lo scambio, il primo pivot è diverso da zero.

**Perché anche un pivot piccolo è pericoloso?**

In aritmetica esatta è sufficiente che il pivot sia diverso da zero. In aritmetica finita, però, un pivot molto piccolo può produrre moltiplicatori enormi.

Per esempio, consideriamo

$$
A=
\begin{pmatrix}
\varepsilon&1\\
1&1
\end{pmatrix},
\qquad 0<\varepsilon\ll1.
$$

Senza scambiare le righe, il primo moltiplicatore è

$$
m_{21}=\frac{1}{\varepsilon},
$$

che può essere molto grande. Le operazioni coinvolgono allora numeri di grandezza molto diversa e possono causare cancellazione e perdita di cifre significative.

Scambiando le righe, il pivot diventa $1$ e il moltiplicatore diventa $\varepsilon$.

### 3.3.2 Pivoting parziale

Al passo $k$ del **pivoting parziale** cerchiamo, nella colonna corrente, l'elemento di modulo massimo tra le righe non ancora utilizzate:

$$
p=\operatorname*{argmax}_{i=k,\ldots,n}|u_{ik}|.
$$

Se $p\neq k$, scambiamo le righe $k$ e $p$. Solo dopo lo scambio procediamo con l'eliminazione.

```{figure} immagini_sorgente/pivoting_parziale.png
---
width: 100%
align: center
---
```
<p align="center">
  <img src="immagini_sorgente/pivoting_parziale.png" width="700">
</p>

La scelta del massimo garantisce che, nella colonna corrente,

$$
|m_{ik}|=\left|\frac{u_{ik}}{u_{kk}}\right|\leq1.
$$

Il pivoting parziale è la strategia usata normalmente per matrici dense generali.

### La matrice di permutazione

Gli scambi di righe vengono rappresentati mediante una **matrice di permutazione** $P$. Essa si ottiene dalla matrice identità eseguendo gli stessi scambi applicati ad $A$.

Le matrici di permutazione sono ortogonali:

$$
P^{-1}=P^T.
$$

Con il pivoting, l'eliminazione non fattorizza direttamente $A$, ma la matrice con le righe permutate:

$$
PA=LU.
$$

Per risolvere $A\mathbf{x}=\mathbf{b}$ moltiplichiamo anche il termine noto per $P$:

$$
PA\mathbf{x}=P\mathbf{b}
\quad\Longrightarrow\quad
LU\mathbf{x}=P\mathbf{b}.
$$

Risolviamo quindi

$$
L\mathbf{y}=P\mathbf{b},
\qquad
U\mathbf{x}=\mathbf{y}.
$$

**Esempio $3\times3$ con pivoting parziale**

Consideriamo

$$
A=
\begin{pmatrix}
0&2&1\\
1&-2&-3\\
2&3&1
\end{pmatrix}.
$$

Il primo pivot candidato è $a_{11}=0$, quindi l'eliminazione senza pivoting fallisce immediatamente.

Nella prima colonna confrontiamo

$$
|0|,\quad |1|,\quad |2|.
$$

Il valore massimo è $2$, che si trova nella terza riga. Scambiamo quindi $R_1$ e $R_3$:

$$
P=
\begin{pmatrix}
0&0&1\\
0&1&0\\
1&0&0
\end{pmatrix},
\qquad
PA=
\begin{pmatrix}
2&3&1\\
1&-2&-3\\
0&2&1
\end{pmatrix}.
$$

*Primo passo di eliminazione*

Dopo lo scambio, il pivot è $2$. I moltiplicatori sono

$$
m_{21}=\frac{1}{2},
\qquad
m_{31}=0.
$$

Eseguiamo

$$
R_2\leftarrow R_2-\frac12R_1,
$$

ottenendo

$$
\begin{pmatrix}
2&3&1\\
0&-\frac72&-\frac72\\
0&2&1
\end{pmatrix}.
$$

Nella seconda colonna confrontiamo $|-7/2|$ e $|2|$. Il pivot di modulo massimo è già nella seconda riga, quindi non sono necessari altri scambi.

*Secondo passo e fattori finali*

Il moltiplicatore della seconda colonna è

$$
m_{32}=\frac{2}{-7/2}=-\frac47.
$$

Dopo l'ultima eliminazione otteniamo

$$
U=
\begin{pmatrix}
2&3&1\\
0&-\frac72&-\frac72\\
0&0&-1
\end{pmatrix}.
$$

I moltiplicatori formano

$$
L=
\begin{pmatrix}
1&0&0\\
\frac12&1&0\\
0&-\frac47&1
\end{pmatrix}.
$$

La fattorizzazione ottenuta è

$$
PA=LU.
$$

In [65]:
import numpy as np
from scipy.linalg import lu

A = np.array([
    [ 2.,  1., 1.],
    [ 4., -6., 0.],
    [-2.,  7., 2.]
])

P, L, U = lu(A)

print("P =\n", P)
print("L =\n", L)
print("U =\n", U)

print(np.allclose(A, P @ L @ U))

P =
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
L =
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5  1.   1. ]]
U =
 [[ 4. -6.  0.]
 [ 0.  4.  1.]
 [ 0.  0.  1.]]
True


### Pivoting e stabilità

Il pivoting parziale riduce il rischio di crescita eccessiva dei moltiplicatori ed è molto efficace nella pratica. Non modifica l'ordine di complessità della fattorizzazione, che resta

$$
\mathcal{O}(n^3).
$$

È importante però distinguere due concetti:

- il **pivoting** riguarda la stabilità dell'algoritmo di eliminazione;
- il **condizionamento** riguarda la sensibilità del problema rispetto a perturbazioni nei dati.

Il pivoting non può rendere ben condizionata una matrice mal condizionata. Può però evitare di aggiungere instabilità numerica non necessaria durante il calcolo.

### 3.4 Fattorizzazione di Cholesky

La fattorizzazione di Cholesky è una variante particolarmente efficiente della fattorizzazione $LU$. Si applica alle matrici reali **simmetriche e definite positive**.

Una matrice $A\in\mathbb{R}^{n\times n}$ è definita positiva se

$$
\mathbf{x}^TA\mathbf{x}>0
\qquad\text{per ogni }\mathbf{x}\neq\mathbf{0}.
$$

In tal caso esiste un'unica matrice triangolare inferiore $L$, con elementi diagonali positivi, tale che

$$
A=LL^T.
$$

*Un esempio* $3\times3$

Consideriamo la matrice simmetrica definita positiva

$$
A=
\begin{pmatrix}
4&2&2\\
2&5&1\\
2&1&5
\end{pmatrix}.
$$

La sua fattorizzazione di Cholesky è

$$
A=LL^T,
\qquad
L=
\begin{pmatrix}
2&0&0\\
1&2&0\\
1&0&2
\end{pmatrix}.
$$

Infatti

$$
LL^T=
\begin{pmatrix}
4&2&2\\
2&5&1\\
2&1&5
\end{pmatrix}=A.
$$

In [66]:
import numpy as np

A = np.array([[4., 2., 2.],
              [2., 5., 1.],
              [2., 1., 5.]])

L = np.linalg.cholesky(A)

print('L =\n', L)
print('\nErrore ||A - LL^T||_2 =', np.linalg.norm(A - L @ L.T))

L =
 [[2. 0. 0.]
 [1. 2. 0.]
 [1. 0. 2.]]

Errore ||A - LL^T||_2 = 0.0


### 4.   Fattorizzazione agli autovalori: teoria e NumPy
Questo notebook introduce la teoria essenziale e applica la decomposizione alla matrice dell'esempio.

 *Autovalori e autovettori*
 
Dato un operatore lineare rappresentato da una matrice quadrata $A\in\mathbb{R}^{n\times n}$, un numero $\lambda$ è un **autovalore** se esiste un vettore non nullo $v$ tale che

$$Av=\lambda v. $$

Il vettore $v$ è l'**autovettore** associato a $\lambda$. La trasformazione $A$ non cambia la direzione di $v$: lo moltiplica soltanto per il fattore $\lambda$.


Riscrivendo l'equazione come $(A-\lambda I)v=0$, esiste una soluzione non nulla soltanto se $A-\lambda I$ è singolare. Pertanto gli autovalori sono le radici del **polinomio caratteristico**

$$p_A(\lambda)=\det(\lambda I-A)=0. $$

Per ogni autovalore, gli autovettori si ottengono risolvendo $(A-\lambda I)v=0$.

 *Diagonalizzazione*
 
Se $A$ possiede $n$ autovettori linearmente indipendenti, è **diagonalizzabile**. Ponendo

$$V=[v_1\;v_2\;\dots\;v_n], \qquad \Lambda=\operatorname{diag}(\lambda_1,\dots,\lambda_n),$$

si ha $AV=V\Lambda$ e quindi

$$A=V\Lambda V^{-1}. $$

Una matrice con autovalori tutti distinti è diagonalizzabile. La diagonalizzabilità può comunque verificarsi anche con autovalori ripetuti, purché esistano abbastanza autovettori indipendenti.

In [67]:
import numpy as np

A = np.array([[ 2.,  1., 1.],
              [ 4., -6., 0.],
              [-2.,  7., 2.]])
A

array([[ 2.,  1.,  1.],
       [ 4., -6.,  0.],
       [-2.,  7.,  2.]])

Per questa matrice il polinomio caratteristico è $p_A(\lambda)=\lambda^3+2\lambda^2-22\lambda+16$. NumPy può calcolarne i coefficienti e le radici numeriche:

In [68]:
coefficienti = np.poly(A)
print("Coefficienti del polinomio caratteristico:", coefficienti)
print("Radici:", np.roots(coefficienti))

Coefficienti del polinomio caratteristico: [  1.   2. -22.  16.]
Radici: [-6.06347233  3.25206391  0.81140842]


 **Calcolo numerico con NumPy**
 
`np.linalg.eig(A)` restituisce gli autovalori e una matrice `V` le cui **colonne** sono gli autovettori corrispondenti. L'ordine degli autovalori non è prestabilito; anche il segno o la fase di un autovettore possono cambiare senza modificarne il significato.

In [69]:
autovalori, V = np.linalg.eig(A)
Lambda = np.diag(autovalori)

print("Autovalori:\n", autovalori)
print("\nAutovettori (in colonna):\n", V)

Autovalori:
 [-6.06347233  3.25206391  0.81140842]

Autovettori (in colonna):
 [[-0.01195857  0.73345874 -0.47148436]
 [ 0.75362427  0.3171006  -0.27687922]
 [-0.65719666  0.60123663  0.83728155]]


In [70]:
A_ricostruita = V @ Lambda @ np.linalg.inv(V)

print("A ricostruita:\n", np.real_if_close(A_ricostruita))
print("\nVerifica A = V @ Lambda @ inv(V):",
      np.allclose(A, A_ricostruita))
print("Verifica A @ V = V @ Lambda:",
      np.allclose(A @ V, V @ Lambda))

A ricostruita:
 [[ 2.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 4.00000000e+00 -6.00000000e+00  4.58049147e-16]
 [-2.00000000e+00  7.00000000e+00  2.00000000e+00]]

Verifica A = V @ Lambda @ inv(V): True
Verifica A @ V = V @ Lambda: True


**Caso delle matrici simmetriche**

Se $A$ è reale e simmetrica, il teorema spettrale garantisce autovalori reali e una base ortonormale di autovettori. È preferibile usare `np.linalg.eigh(A)` e si ottiene $A=V\Lambda V^T$, perché $V^{-1}=V^T$. Per una matrice generale, invece, gli autovalori e gli autovettori possono essere complessi.